services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: interview_mysql_dev
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: interview_system
      MYSQL_USER: interview_user
      MYSQL_PASSWORD: interview_pass
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - interview_network_dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: interview_redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - interview_network_dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  mysql_data_dev:
  redis_data_dev:

networks:
  interview_network_dev:
    driver: bridge

